//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WABlockchain.SWLNBlockChain {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SWLNBlockChain.ISWLNBlockchain")]
    public interface ISWLNBlockchain {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/DoWork", ReplyAction="http://tempuri.org/ISWLNBlockchain/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/DoWork", ReplyAction="http://tempuri.org/ISWLNBlockchain/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISWLNBlockchainChannel : WABlockchain.SWLNBlockChain.ISWLNBlockchain, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWLNBlockchainClient : System.ServiceModel.ClientBase<WABlockchain.SWLNBlockChain.ISWLNBlockchain>, WABlockchain.SWLNBlockChain.ISWLNBlockchain {
        
        public SWLNBlockchainClient() {
        }
        
        public SWLNBlockchainClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWLNBlockchainClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWLNBlockchainClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWLNBlockchainClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
