//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WABlockchain.SWADBlockchainService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EBTittle", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EBTittle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdTittlesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carreerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dateDeliveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string facultyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string impressionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime lastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime registerDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusDeliveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdTittles {
            get {
                return this.IdTittlesField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTittlesField, value) != true)) {
                    this.IdTittlesField = value;
                    this.RaisePropertyChanged("IdTittles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carreer {
            get {
                return this.carreerField;
            }
            set {
                if ((object.ReferenceEquals(this.carreerField, value) != true)) {
                    this.carreerField = value;
                    this.RaisePropertyChanged("carreer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dateDelivery {
            get {
                return this.dateDeliveryField;
            }
            set {
                if ((object.ReferenceEquals(this.dateDeliveryField, value) != true)) {
                    this.dateDeliveryField = value;
                    this.RaisePropertyChanged("dateDelivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string faculty {
            get {
                return this.facultyField;
            }
            set {
                if ((object.ReferenceEquals(this.facultyField, value) != true)) {
                    this.facultyField = value;
                    this.RaisePropertyChanged("faculty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fullNameField, value) != true)) {
                    this.fullNameField = value;
                    this.RaisePropertyChanged("fullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idUser {
            get {
                return this.idUserField;
            }
            set {
                if ((object.ReferenceEquals(this.idUserField, value) != true)) {
                    this.idUserField = value;
                    this.RaisePropertyChanged("idUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string impression {
            get {
                return this.impressionField;
            }
            set {
                if ((object.ReferenceEquals(this.impressionField, value) != true)) {
                    this.impressionField = value;
                    this.RaisePropertyChanged("impression");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime lastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                if ((this.lastUpdateField.Equals(value) != true)) {
                    this.lastUpdateField = value;
                    this.RaisePropertyChanged("lastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime registerDate {
            get {
                return this.registerDateField;
            }
            set {
                if ((this.registerDateField.Equals(value) != true)) {
                    this.registerDateField = value;
                    this.RaisePropertyChanged("registerDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string statusDelivery {
            get {
                return this.statusDeliveryField;
            }
            set {
                if ((object.ReferenceEquals(this.statusDeliveryField, value) != true)) {
                    this.statusDeliveryField = value;
                    this.RaisePropertyChanged("statusDelivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string statusTitle {
            get {
                return this.statusTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.statusTitleField, value) != true)) {
                    this.statusTitleField = value;
                    this.RaisePropertyChanged("statusTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SWADBlockchainService.ISWADNETBlockchain")]
    public interface ISWADNETBlockchain {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWADNETBlockchain/Obtener_BTitle_O_statusTitle", ReplyAction="http://tempuri.org/ISWADNETBlockchain/Obtener_BTitle_O_statusTitleResponse")]
        WABlockchain.SWADBlockchainService.EBTittle[] Obtener_BTitle_O_statusTitle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWADNETBlockchain/Obtener_BTitle_O_statusTitle", ReplyAction="http://tempuri.org/ISWADNETBlockchain/Obtener_BTitle_O_statusTitleResponse")]
        System.Threading.Tasks.Task<WABlockchain.SWADBlockchainService.EBTittle[]> Obtener_BTitle_O_statusTitleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWADNETBlockchain/Actualizar_BTitle_A_statusTittle", ReplyAction="http://tempuri.org/ISWADNETBlockchain/Actualizar_BTitle_A_statusTittleResponse")]
        void Actualizar_BTitle_A_statusTittle(WABlockchain.SWADBlockchainService.EBTittle eBTittle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWADNETBlockchain/Actualizar_BTitle_A_statusTittle", ReplyAction="http://tempuri.org/ISWADNETBlockchain/Actualizar_BTitle_A_statusTittleResponse")]
        System.Threading.Tasks.Task Actualizar_BTitle_A_statusTittleAsync(WABlockchain.SWADBlockchainService.EBTittle eBTittle);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISWADNETBlockchainChannel : WABlockchain.SWADBlockchainService.ISWADNETBlockchain, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWADNETBlockchainClient : System.ServiceModel.ClientBase<WABlockchain.SWADBlockchainService.ISWADNETBlockchain>, WABlockchain.SWADBlockchainService.ISWADNETBlockchain {
        
        public SWADNETBlockchainClient() {
        }
        
        public SWADNETBlockchainClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWADNETBlockchainClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWADNETBlockchainClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWADNETBlockchainClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WABlockchain.SWADBlockchainService.EBTittle[] Obtener_BTitle_O_statusTitle() {
            return base.Channel.Obtener_BTitle_O_statusTitle();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWADBlockchainService.EBTittle[]> Obtener_BTitle_O_statusTitleAsync() {
            return base.Channel.Obtener_BTitle_O_statusTitleAsync();
        }
        
        public void Actualizar_BTitle_A_statusTittle(WABlockchain.SWADBlockchainService.EBTittle eBTittle) {
            base.Channel.Actualizar_BTitle_A_statusTittle(eBTittle);
        }
        
        public System.Threading.Tasks.Task Actualizar_BTitle_A_statusTittleAsync(WABlockchain.SWADBlockchainService.EBTittle eBTittle) {
            return base.Channel.Actualizar_BTitle_A_statusTittleAsync(eBTittle);
        }
    }
}
