//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WABlockchain.SWLNBlockchainService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EBUser", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EBUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIExtraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellphoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdRolUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNetvalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CI {
            get {
                return this.CIField;
            }
            set {
                if ((object.ReferenceEquals(this.CIField, value) != true)) {
                    this.CIField = value;
                    this.RaisePropertyChanged("CI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CIExtra {
            get {
                return this.CIExtraField;
            }
            set {
                if ((object.ReferenceEquals(this.CIExtraField, value) != true)) {
                    this.CIExtraField = value;
                    this.RaisePropertyChanged("CIExtra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cellphone {
            get {
                return this.CellphoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CellphoneField, value) != true)) {
                    this.CellphoneField = value;
                    this.RaisePropertyChanged("Cellphone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fullname {
            get {
                return this.FullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullnameField, value) != true)) {
                    this.FullnameField = value;
                    this.RaisePropertyChanged("Fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRolUser {
            get {
                return this.IdRolUserField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRolUserField, value) != true)) {
                    this.IdRolUserField = value;
                    this.RaisePropertyChanged("IdRolUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUser {
            get {
                return this.IdUserField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUserField, value) != true)) {
                    this.IdUserField = value;
                    this.RaisePropertyChanged("IdUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserNetvalle {
            get {
                return this.UserNetvalleField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNetvalleField, value) != true)) {
                    this.UserNetvalleField = value;
                    this.RaisePropertyChanged("UserNetvalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EBTittle", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EBTittle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdTittlesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carreerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateDeliveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string facultyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fullNameTituladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idQrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime lastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime registerDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusDeliveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdTittles {
            get {
                return this.IdTittlesField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTittlesField, value) != true)) {
                    this.IdTittlesField = value;
                    this.RaisePropertyChanged("IdTittles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carreer {
            get {
                return this.carreerField;
            }
            set {
                if ((object.ReferenceEquals(this.carreerField, value) != true)) {
                    this.carreerField = value;
                    this.RaisePropertyChanged("carreer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateDelivery {
            get {
                return this.dateDeliveryField;
            }
            set {
                if ((this.dateDeliveryField.Equals(value) != true)) {
                    this.dateDeliveryField = value;
                    this.RaisePropertyChanged("dateDelivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string faculty {
            get {
                return this.facultyField;
            }
            set {
                if ((object.ReferenceEquals(this.facultyField, value) != true)) {
                    this.facultyField = value;
                    this.RaisePropertyChanged("faculty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fullNameTitulado {
            get {
                return this.fullNameTituladoField;
            }
            set {
                if ((object.ReferenceEquals(this.fullNameTituladoField, value) != true)) {
                    this.fullNameTituladoField = value;
                    this.RaisePropertyChanged("fullNameTitulado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idQr {
            get {
                return this.idQrField;
            }
            set {
                if ((object.ReferenceEquals(this.idQrField, value) != true)) {
                    this.idQrField = value;
                    this.RaisePropertyChanged("idQr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idToken {
            get {
                return this.idTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.idTokenField, value) != true)) {
                    this.idTokenField = value;
                    this.RaisePropertyChanged("idToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idUser {
            get {
                return this.idUserField;
            }
            set {
                if ((object.ReferenceEquals(this.idUserField, value) != true)) {
                    this.idUserField = value;
                    this.RaisePropertyChanged("idUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime lastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                if ((this.lastUpdateField.Equals(value) != true)) {
                    this.lastUpdateField = value;
                    this.RaisePropertyChanged("lastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime registerDate {
            get {
                return this.registerDateField;
            }
            set {
                if ((this.registerDateField.Equals(value) != true)) {
                    this.registerDateField = value;
                    this.RaisePropertyChanged("registerDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string statusDelivery {
            get {
                return this.statusDeliveryField;
            }
            set {
                if ((object.ReferenceEquals(this.statusDeliveryField, value) != true)) {
                    this.statusDeliveryField = value;
                    this.RaisePropertyChanged("statusDelivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string statusTitle {
            get {
                return this.statusTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.statusTitleField, value) != true)) {
                    this.statusTitleField = value;
                    this.RaisePropertyChanged("statusTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EBRoluser", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EBRoluser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idrolUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idrolUser {
            get {
                return this.idrolUserField;
            }
            set {
                if ((object.ReferenceEquals(this.idrolUserField, value) != true)) {
                    this.idrolUserField = value;
                    this.RaisePropertyChanged("idrolUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ENPerson", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ENPerson : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtCIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCareerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CI {
            get {
                return this.CIField;
            }
            set {
                if ((object.ReferenceEquals(this.CIField, value) != true)) {
                    this.CIField = value;
                    this.RaisePropertyChanged("CI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtCI {
            get {
                return this.ExtCIField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtCIField, value) != true)) {
                    this.ExtCIField = value;
                    this.RaisePropertyChanged("ExtCI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fullname {
            get {
                return this.FullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullnameField, value) != true)) {
                    this.FullnameField = value;
                    this.RaisePropertyChanged("Fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDCareer {
            get {
                return this.IDCareerField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCareerField, value) != true)) {
                    this.IDCareerField = value;
                    this.RaisePropertyChanged("IDCareer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDPerson {
            get {
                return this.IDPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.IDPersonField, value) != true)) {
                    this.IDPersonField = value;
                    this.RaisePropertyChanged("IDPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ENCareer", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ENCareer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CareerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCareerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SedeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CareerName {
            get {
                return this.CareerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CareerNameField, value) != true)) {
                    this.CareerNameField = value;
                    this.RaisePropertyChanged("CareerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacultyName {
            get {
                return this.FacultyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyNameField, value) != true)) {
                    this.FacultyNameField = value;
                    this.RaisePropertyChanged("FacultyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDCareer {
            get {
                return this.IDCareerField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCareerField, value) != true)) {
                    this.IDCareerField = value;
                    this.RaisePropertyChanged("IDCareer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SedeName {
            get {
                return this.SedeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SedeNameField, value) != true)) {
                    this.SedeNameField = value;
                    this.RaisePropertyChanged("SedeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IUserCareerCompleja", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class IUserCareerCompleja : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CareerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtCIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCareerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SedeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CI {
            get {
                return this.CIField;
            }
            set {
                if ((object.ReferenceEquals(this.CIField, value) != true)) {
                    this.CIField = value;
                    this.RaisePropertyChanged("CI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CareerName {
            get {
                return this.CareerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CareerNameField, value) != true)) {
                    this.CareerNameField = value;
                    this.RaisePropertyChanged("CareerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtCI {
            get {
                return this.ExtCIField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtCIField, value) != true)) {
                    this.ExtCIField = value;
                    this.RaisePropertyChanged("ExtCI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacultyName {
            get {
                return this.FacultyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyNameField, value) != true)) {
                    this.FacultyNameField = value;
                    this.RaisePropertyChanged("FacultyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fullname {
            get {
                return this.FullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullnameField, value) != true)) {
                    this.FullnameField = value;
                    this.RaisePropertyChanged("Fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDCareer {
            get {
                return this.IDCareerField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCareerField, value) != true)) {
                    this.IDCareerField = value;
                    this.RaisePropertyChanged("IDCareer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDPerson {
            get {
                return this.IDPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.IDPersonField, value) != true)) {
                    this.IDPersonField = value;
                    this.RaisePropertyChanged("IDPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SedeName {
            get {
                return this.SedeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SedeNameField, value) != true)) {
                    this.SedeNameField = value;
                    this.RaisePropertyChanged("SedeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SWLNBlockchainService.ISWLNBlockchain")]
    public interface ISWLNBlockchain {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_RolUser_O_Search", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_RolUser_O_SearchResponse")]
        WABlockchain.SWLNBlockchainService.EBUser Obtener_RolUser_O_Search(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_RolUser_O_Search", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_RolUser_O_SearchResponse")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBUser> Obtener_RolUser_O_SearchAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_User_O", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_User_OResponse")]
        WABlockchain.SWLNBlockchainService.EBUser[] Obtener_User_O();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_User_O", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_User_OResponse")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBUser[]> Obtener_User_OAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/btener_BUser_O_iduser", ReplyAction="http://tempuri.org/ISWLNBlockchain/btener_BUser_O_iduserResponse")]
        WABlockchain.SWLNBlockchainService.EBUser btener_BUser_O_iduser(string Id_Carrera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/btener_BUser_O_iduser", ReplyAction="http://tempuri.org/ISWLNBlockchain/btener_BUser_O_iduserResponse")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBUser> btener_BUser_O_iduserAsync(string Id_Carrera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Insertar_BUser_I_idUser_email", ReplyAction="http://tempuri.org/ISWLNBlockchain/Insertar_BUser_I_idUser_emailResponse")]
        void Insertar_BUser_I_idUser_email(string Id_User, string email, string password, string status, string userNetvalle, string idrolUser, string Fullname, string Cellphone, string Ci, string description, string ciExtra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Insertar_BUser_I_idUser_email", ReplyAction="http://tempuri.org/ISWLNBlockchain/Insertar_BUser_I_idUser_emailResponse")]
        System.Threading.Tasks.Task Insertar_BUser_I_idUser_emailAsync(string Id_User, string email, string password, string status, string userNetvalle, string idrolUser, string Fullname, string Cellphone, string Ci, string description, string ciExtra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Insertar_BUser_I", ReplyAction="http://tempuri.org/ISWLNBlockchain/Insertar_BUser_IResponse")]
        void Insertar_BUser_I(string Id_User, string email, string password, string status, string userNetvalle, string idrolUser, string Fullname, string Cellphone, string Ci, string description, string ciExtra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Insertar_BUser_I", ReplyAction="http://tempuri.org/ISWLNBlockchain/Insertar_BUser_IResponse")]
        System.Threading.Tasks.Task Insertar_BUser_IAsync(string Id_User, string email, string password, string status, string userNetvalle, string idrolUser, string Fullname, string Cellphone, string Ci, string description, string ciExtra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Actualizar_BUser_I_idUser_email", ReplyAction="http://tempuri.org/ISWLNBlockchain/Actualizar_BUser_I_idUser_emailResponse")]
        void Actualizar_BUser_I_idUser_email(string Email, string password, string userNetvalle, string idrolUser, string idTitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Actualizar_BUser_I_idUser_email", ReplyAction="http://tempuri.org/ISWLNBlockchain/Actualizar_BUser_I_idUser_emailResponse")]
        System.Threading.Tasks.Task Actualizar_BUser_I_idUser_emailAsync(string Email, string password, string userNetvalle, string idrolUser, string idTitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Insertar_BTitle_I_idTitle_faculty", ReplyAction="http://tempuri.org/ISWLNBlockchain/Insertar_BTitle_I_idTitle_facultyResponse")]
        void Insertar_BTitle_I_idTitle_faculty(string faculty, string carreer, string statusTittle, System.DateTime dateDelivery, string statusDelivery, string idUser, string fullnameTitulado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Insertar_BTitle_I_idTitle_faculty", ReplyAction="http://tempuri.org/ISWLNBlockchain/Insertar_BTitle_I_idTitle_facultyResponse")]
        System.Threading.Tasks.Task Insertar_BTitle_I_idTitle_facultyAsync(string faculty, string carreer, string statusTittle, System.DateTime dateDelivery, string statusDelivery, string idUser, string fullnameTitulado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Insertar_BTitle", ReplyAction="http://tempuri.org/ISWLNBlockchain/Insertar_BTitleResponse")]
        void Insertar_BTitle(string idTittle, string faculty, string carreer, string idUser, string fullnameTitulado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Insertar_BTitle", ReplyAction="http://tempuri.org/ISWLNBlockchain/Insertar_BTitleResponse")]
        System.Threading.Tasks.Task Insertar_BTitleAsync(string idTittle, string faculty, string carreer, string idUser, string fullnameTitulado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Search_BTitle", ReplyAction="http://tempuri.org/ISWLNBlockchain/Search_BTitleResponse")]
        WABlockchain.SWLNBlockchainService.EBTittle[] Search_BTitle(string name, string carreer, string faculty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Search_BTitle", ReplyAction="http://tempuri.org/ISWLNBlockchain/Search_BTitleResponse")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> Search_BTitleAsync(string name, string carreer, string faculty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_Title_O", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_Title_OResponse")]
        WABlockchain.SWLNBlockchainService.EBTittle[] Obtener_Title_O();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_Title_O", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_Title_OResponse")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> Obtener_Title_OAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_Title_1", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_Title_1Response")]
        WABlockchain.SWLNBlockchainService.EBTittle[] Obtener_Title_1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_Title_1", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_Title_1Response")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> Obtener_Title_1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_Title_2", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_Title_2Response")]
        WABlockchain.SWLNBlockchainService.EBTittle[] Obtener_Title_2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_Title_2", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_Title_2Response")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> Obtener_Title_2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Actualizar_ITitle_statusTitle", ReplyAction="http://tempuri.org/ISWLNBlockchain/Actualizar_ITitle_statusTitleResponse")]
        void Actualizar_ITitle_statusTitle(string Id_Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Actualizar_ITitle_statusTitle", ReplyAction="http://tempuri.org/ISWLNBlockchain/Actualizar_ITitle_statusTitleResponse")]
        System.Threading.Tasks.Task Actualizar_ITitle_statusTitleAsync(string Id_Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_3", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_3Response")]
        void BTittle_update_statusTittle_3(string Id_Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_3", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_3Response")]
        System.Threading.Tasks.Task BTittle_update_statusTittle_3Async(string Id_Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_4", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_4Response")]
        void BTittle_update_statusTittle_4(string Id_Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_4", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_4Response")]
        System.Threading.Tasks.Task BTittle_update_statusTittle_4Async(string Id_Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_5", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_5Response")]
        void BTittle_update_statusTittle_5(string Id_Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_5", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_5Response")]
        System.Threading.Tasks.Task BTittle_update_statusTittle_5Async(string Id_Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_6", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_6Response")]
        void BTittle_update_statusTittle_6(string Id_Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_6", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_6Response")]
        System.Threading.Tasks.Task BTittle_update_statusTittle_6Async(string Id_Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_7", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_7Response")]
        void BTittle_update_statusTittle_7(string Id_Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_7", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_update_statusTittle_7Response")]
        System.Threading.Tasks.Task BTittle_update_statusTittle_7Async(string Id_Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_O_State2", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_O_State2Response")]
        WABlockchain.SWLNBlockchainService.EBTittle[] BTittle_O_State2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_O_State2", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_O_State2Response")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> BTittle_O_State2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_O_State3", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_O_State3Response")]
        WABlockchain.SWLNBlockchainService.EBTittle[] BTittle_O_State3();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_O_State3", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_O_State3Response")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> BTittle_O_State3Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_O_State4", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_O_State4Response")]
        WABlockchain.SWLNBlockchainService.EBTittle[] BTittle_O_State4();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_O_State4", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_O_State4Response")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> BTittle_O_State4Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_O_State5", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_O_State5Response")]
        WABlockchain.SWLNBlockchainService.EBTittle[] BTittle_O_State5();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_O_State5", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_O_State5Response")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> BTittle_O_State5Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_O_State6", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_O_State6Response")]
        WABlockchain.SWLNBlockchainService.EBTittle[] BTittle_O_State6();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_O_State6", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_O_State6Response")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> BTittle_O_State6Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_O_State7", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_O_State7Response")]
        WABlockchain.SWLNBlockchainService.EBTittle[] BTittle_O_State7();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_O_State7", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_O_State7Response")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> BTittle_O_State7Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_O_TO_Upload", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_O_TO_UploadResponse")]
        WABlockchain.SWLNBlockchainService.EBTittle[] BTittle_O_TO_Upload();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/BTittle_O_TO_Upload", ReplyAction="http://tempuri.org/ISWLNBlockchain/BTittle_O_TO_UploadResponse")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> BTittle_O_TO_UploadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Actualizar_ITitle_statusTitle_2", ReplyAction="http://tempuri.org/ISWLNBlockchain/Actualizar_ITitle_statusTitle_2Response")]
        void Actualizar_ITitle_statusTitle_2(string Id_Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Actualizar_ITitle_statusTitle_2", ReplyAction="http://tempuri.org/ISWLNBlockchain/Actualizar_ITitle_statusTitle_2Response")]
        System.Threading.Tasks.Task Actualizar_ITitle_statusTitle_2Async(string Id_Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Actualizar_ITitle_statusTitle_1", ReplyAction="http://tempuri.org/ISWLNBlockchain/Actualizar_ITitle_statusTitle_1Response")]
        void Actualizar_ITitle_statusTitle_1(string Id_Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Actualizar_ITitle_statusTitle_1", ReplyAction="http://tempuri.org/ISWLNBlockchain/Actualizar_ITitle_statusTitle_1Response")]
        System.Threading.Tasks.Task Actualizar_ITitle_statusTitle_1Async(string Id_Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Eliminar_ITitle_statusTitle", ReplyAction="http://tempuri.org/ISWLNBlockchain/Eliminar_ITitle_statusTitleResponse")]
        void Eliminar_ITitle_statusTitle(string Id_Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Eliminar_ITitle_statusTitle", ReplyAction="http://tempuri.org/ISWLNBlockchain/Eliminar_ITitle_statusTitleResponse")]
        System.Threading.Tasks.Task Eliminar_ITitle_statusTitleAsync(string Id_Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Actualizar_ITitle", ReplyAction="http://tempuri.org/ISWLNBlockchain/Actualizar_ITitleResponse")]
        void Actualizar_ITitle(string Id_Title, string carreer, string faculty, string fullName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Actualizar_ITitle", ReplyAction="http://tempuri.org/ISWLNBlockchain/Actualizar_ITitleResponse")]
        System.Threading.Tasks.Task Actualizar_ITitleAsync(string Id_Title, string carreer, string faculty, string fullName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Actualizar_BTittle_ConfirmarEntrega", ReplyAction="http://tempuri.org/ISWLNBlockchain/Actualizar_BTittle_ConfirmarEntregaResponse")]
        void Actualizar_BTittle_ConfirmarEntrega(string fullName, System.DateTime fecha, string modo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Actualizar_BTittle_ConfirmarEntrega", ReplyAction="http://tempuri.org/ISWLNBlockchain/Actualizar_BTittle_ConfirmarEntregaResponse")]
        System.Threading.Tasks.Task Actualizar_BTittle_ConfirmarEntregaAsync(string fullName, System.DateTime fecha, string modo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_RolUser_O", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_RolUser_OResponse")]
        WABlockchain.SWLNBlockchainService.EBRoluser[] Obtener_RolUser_O();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_RolUser_O", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_RolUser_OResponse")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBRoluser[]> Obtener_RolUser_OAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/UltimoID_O_NombreTablaSinElCaracterI", ReplyAction="http://tempuri.org/ISWLNBlockchain/UltimoID_O_NombreTablaSinElCaracterIResponse")]
        string UltimoID_O_NombreTablaSinElCaracterI(string NombreTabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/UltimoID_O_NombreTablaSinElCaracterI", ReplyAction="http://tempuri.org/ISWLNBlockchain/UltimoID_O_NombreTablaSinElCaracterIResponse")]
        System.Threading.Tasks.Task<string> UltimoID_O_NombreTablaSinElCaracterIAsync(string NombreTabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/SiguienteID_O_NombreTablaSinElCaracterI", ReplyAction="http://tempuri.org/ISWLNBlockchain/SiguienteID_O_NombreTablaSinElCaracterIRespons" +
            "e")]
        string SiguienteID_O_NombreTablaSinElCaracterI(string NombreTabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/SiguienteID_O_NombreTablaSinElCaracterI", ReplyAction="http://tempuri.org/ISWLNBlockchain/SiguienteID_O_NombreTablaSinElCaracterIRespons" +
            "e")]
        System.Threading.Tasks.Task<string> SiguienteID_O_NombreTablaSinElCaracterIAsync(string NombreTabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_Persona_O_Estudiante", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_Persona_O_EstudianteResponse")]
        WABlockchain.SWLNBlockchainService.ENPerson Obtener_Persona_O_Estudiante();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_Persona_O_Estudiante", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_Persona_O_EstudianteResponse")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.ENPerson> Obtener_Persona_O_EstudianteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_Persona_O_EstudianteL", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_Persona_O_EstudianteLResponse")]
        WABlockchain.SWLNBlockchainService.ENPerson[] Obtener_Persona_O_EstudianteL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_Persona_O_EstudianteL", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_Persona_O_EstudianteLResponse")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.ENPerson[]> Obtener_Persona_O_EstudianteLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_Persona_O_Nombre", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_Persona_O_NombreResponse")]
        WABlockchain.SWLNBlockchainService.ENPerson[] Obtener_Persona_O_Nombre(string Fullname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_Persona_O_Nombre", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_Persona_O_NombreResponse")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.ENPerson[]> Obtener_Persona_O_NombreAsync(string Fullname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_Persona_O", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_Persona_OResponse")]
        WABlockchain.SWLNBlockchainService.ENPerson[] Obtener_Persona_O();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_Persona_O", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_Persona_OResponse")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.ENPerson[]> Obtener_Persona_OAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_Carrerra_O_ID_Pedro", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_Carrerra_O_ID_PedroResponse")]
        WABlockchain.SWLNBlockchainService.ENCareer Obtener_Carrerra_O_ID_Pedro(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_Carrerra_O_ID_Pedro", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_Carrerra_O_ID_PedroResponse")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.ENCareer> Obtener_Carrerra_O_ID_PedroAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/U_Obtener_UserCareerComplejas_O_Est", ReplyAction="http://tempuri.org/ISWLNBlockchain/U_Obtener_UserCareerComplejas_O_EstResponse")]
        WABlockchain.SWLNBlockchainService.IUserCareerCompleja[] U_Obtener_UserCareerComplejas_O_Est();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/U_Obtener_UserCareerComplejas_O_Est", ReplyAction="http://tempuri.org/ISWLNBlockchain/U_Obtener_UserCareerComplejas_O_EstResponse")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.IUserCareerCompleja[]> U_Obtener_UserCareerComplejas_O_EstAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/U_Obtener_UserCareerComplejas_O_Person", ReplyAction="http://tempuri.org/ISWLNBlockchain/U_Obtener_UserCareerComplejas_O_PersonResponse" +
            "")]
        WABlockchain.SWLNBlockchainService.IUserCareerCompleja[] U_Obtener_UserCareerComplejas_O_Person();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/U_Obtener_UserCareerComplejas_O_Person", ReplyAction="http://tempuri.org/ISWLNBlockchain/U_Obtener_UserCareerComplejas_O_PersonResponse" +
            "")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.IUserCareerCompleja[]> U_Obtener_UserCareerComplejas_O_PersonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/U_Obtener_UserCareerComplejas_O_Est_Bus", ReplyAction="http://tempuri.org/ISWLNBlockchain/U_Obtener_UserCareerComplejas_O_Est_BusRespons" +
            "e")]
        WABlockchain.SWLNBlockchainService.IUserCareerCompleja[] U_Obtener_UserCareerComplejas_O_Est_Bus(string Fullname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/U_Obtener_UserCareerComplejas_O_Est_Bus", ReplyAction="http://tempuri.org/ISWLNBlockchain/U_Obtener_UserCareerComplejas_O_Est_BusRespons" +
            "e")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.IUserCareerCompleja[]> U_Obtener_UserCareerComplejas_O_Est_BusAsync(string Fullname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/U_Obtener_UserCareerComplejas_O_Est_ID", ReplyAction="http://tempuri.org/ISWLNBlockchain/U_Obtener_UserCareerComplejas_O_Est_IDResponse" +
            "")]
        WABlockchain.SWLNBlockchainService.IUserCareerCompleja[] U_Obtener_UserCareerComplejas_O_Est_ID(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/U_Obtener_UserCareerComplejas_O_Est_ID", ReplyAction="http://tempuri.org/ISWLNBlockchain/U_Obtener_UserCareerComplejas_O_Est_IDResponse" +
            "")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.IUserCareerCompleja[]> U_Obtener_UserCareerComplejas_O_Est_IDAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISWLNBlockchainChannel : WABlockchain.SWLNBlockchainService.ISWLNBlockchain, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWLNBlockchainClient : System.ServiceModel.ClientBase<WABlockchain.SWLNBlockchainService.ISWLNBlockchain>, WABlockchain.SWLNBlockchainService.ISWLNBlockchain {
        
        public SWLNBlockchainClient() {
        }
        
        public SWLNBlockchainClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWLNBlockchainClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWLNBlockchainClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWLNBlockchainClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WABlockchain.SWLNBlockchainService.EBUser Obtener_RolUser_O_Search(string email, string password) {
            return base.Channel.Obtener_RolUser_O_Search(email, password);
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBUser> Obtener_RolUser_O_SearchAsync(string email, string password) {
            return base.Channel.Obtener_RolUser_O_SearchAsync(email, password);
        }
        
        public WABlockchain.SWLNBlockchainService.EBUser[] Obtener_User_O() {
            return base.Channel.Obtener_User_O();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBUser[]> Obtener_User_OAsync() {
            return base.Channel.Obtener_User_OAsync();
        }
        
        public WABlockchain.SWLNBlockchainService.EBUser btener_BUser_O_iduser(string Id_Carrera) {
            return base.Channel.btener_BUser_O_iduser(Id_Carrera);
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBUser> btener_BUser_O_iduserAsync(string Id_Carrera) {
            return base.Channel.btener_BUser_O_iduserAsync(Id_Carrera);
        }
        
        public void Insertar_BUser_I_idUser_email(string Id_User, string email, string password, string status, string userNetvalle, string idrolUser, string Fullname, string Cellphone, string Ci, string description, string ciExtra) {
            base.Channel.Insertar_BUser_I_idUser_email(Id_User, email, password, status, userNetvalle, idrolUser, Fullname, Cellphone, Ci, description, ciExtra);
        }
        
        public System.Threading.Tasks.Task Insertar_BUser_I_idUser_emailAsync(string Id_User, string email, string password, string status, string userNetvalle, string idrolUser, string Fullname, string Cellphone, string Ci, string description, string ciExtra) {
            return base.Channel.Insertar_BUser_I_idUser_emailAsync(Id_User, email, password, status, userNetvalle, idrolUser, Fullname, Cellphone, Ci, description, ciExtra);
        }
        
        public void Insertar_BUser_I(string Id_User, string email, string password, string status, string userNetvalle, string idrolUser, string Fullname, string Cellphone, string Ci, string description, string ciExtra) {
            base.Channel.Insertar_BUser_I(Id_User, email, password, status, userNetvalle, idrolUser, Fullname, Cellphone, Ci, description, ciExtra);
        }
        
        public System.Threading.Tasks.Task Insertar_BUser_IAsync(string Id_User, string email, string password, string status, string userNetvalle, string idrolUser, string Fullname, string Cellphone, string Ci, string description, string ciExtra) {
            return base.Channel.Insertar_BUser_IAsync(Id_User, email, password, status, userNetvalle, idrolUser, Fullname, Cellphone, Ci, description, ciExtra);
        }
        
        public void Actualizar_BUser_I_idUser_email(string Email, string password, string userNetvalle, string idrolUser, string idTitle) {
            base.Channel.Actualizar_BUser_I_idUser_email(Email, password, userNetvalle, idrolUser, idTitle);
        }
        
        public System.Threading.Tasks.Task Actualizar_BUser_I_idUser_emailAsync(string Email, string password, string userNetvalle, string idrolUser, string idTitle) {
            return base.Channel.Actualizar_BUser_I_idUser_emailAsync(Email, password, userNetvalle, idrolUser, idTitle);
        }
        
        public void Insertar_BTitle_I_idTitle_faculty(string faculty, string carreer, string statusTittle, System.DateTime dateDelivery, string statusDelivery, string idUser, string fullnameTitulado) {
            base.Channel.Insertar_BTitle_I_idTitle_faculty(faculty, carreer, statusTittle, dateDelivery, statusDelivery, idUser, fullnameTitulado);
        }
        
        public System.Threading.Tasks.Task Insertar_BTitle_I_idTitle_facultyAsync(string faculty, string carreer, string statusTittle, System.DateTime dateDelivery, string statusDelivery, string idUser, string fullnameTitulado) {
            return base.Channel.Insertar_BTitle_I_idTitle_facultyAsync(faculty, carreer, statusTittle, dateDelivery, statusDelivery, idUser, fullnameTitulado);
        }
        
        public void Insertar_BTitle(string idTittle, string faculty, string carreer, string idUser, string fullnameTitulado) {
            base.Channel.Insertar_BTitle(idTittle, faculty, carreer, idUser, fullnameTitulado);
        }
        
        public System.Threading.Tasks.Task Insertar_BTitleAsync(string idTittle, string faculty, string carreer, string idUser, string fullnameTitulado) {
            return base.Channel.Insertar_BTitleAsync(idTittle, faculty, carreer, idUser, fullnameTitulado);
        }
        
        public WABlockchain.SWLNBlockchainService.EBTittle[] Search_BTitle(string name, string carreer, string faculty) {
            return base.Channel.Search_BTitle(name, carreer, faculty);
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> Search_BTitleAsync(string name, string carreer, string faculty) {
            return base.Channel.Search_BTitleAsync(name, carreer, faculty);
        }
        
        public WABlockchain.SWLNBlockchainService.EBTittle[] Obtener_Title_O() {
            return base.Channel.Obtener_Title_O();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> Obtener_Title_OAsync() {
            return base.Channel.Obtener_Title_OAsync();
        }
        
        public WABlockchain.SWLNBlockchainService.EBTittle[] Obtener_Title_1() {
            return base.Channel.Obtener_Title_1();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> Obtener_Title_1Async() {
            return base.Channel.Obtener_Title_1Async();
        }
        
        public WABlockchain.SWLNBlockchainService.EBTittle[] Obtener_Title_2() {
            return base.Channel.Obtener_Title_2();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> Obtener_Title_2Async() {
            return base.Channel.Obtener_Title_2Async();
        }
        
        public void Actualizar_ITitle_statusTitle(string Id_Title) {
            base.Channel.Actualizar_ITitle_statusTitle(Id_Title);
        }
        
        public System.Threading.Tasks.Task Actualizar_ITitle_statusTitleAsync(string Id_Title) {
            return base.Channel.Actualizar_ITitle_statusTitleAsync(Id_Title);
        }
        
        public void BTittle_update_statusTittle_3(string Id_Title) {
            base.Channel.BTittle_update_statusTittle_3(Id_Title);
        }
        
        public System.Threading.Tasks.Task BTittle_update_statusTittle_3Async(string Id_Title) {
            return base.Channel.BTittle_update_statusTittle_3Async(Id_Title);
        }
        
        public void BTittle_update_statusTittle_4(string Id_Title) {
            base.Channel.BTittle_update_statusTittle_4(Id_Title);
        }
        
        public System.Threading.Tasks.Task BTittle_update_statusTittle_4Async(string Id_Title) {
            return base.Channel.BTittle_update_statusTittle_4Async(Id_Title);
        }
        
        public void BTittle_update_statusTittle_5(string Id_Title) {
            base.Channel.BTittle_update_statusTittle_5(Id_Title);
        }
        
        public System.Threading.Tasks.Task BTittle_update_statusTittle_5Async(string Id_Title) {
            return base.Channel.BTittle_update_statusTittle_5Async(Id_Title);
        }
        
        public void BTittle_update_statusTittle_6(string Id_Title) {
            base.Channel.BTittle_update_statusTittle_6(Id_Title);
        }
        
        public System.Threading.Tasks.Task BTittle_update_statusTittle_6Async(string Id_Title) {
            return base.Channel.BTittle_update_statusTittle_6Async(Id_Title);
        }
        
        public void BTittle_update_statusTittle_7(string Id_Title) {
            base.Channel.BTittle_update_statusTittle_7(Id_Title);
        }
        
        public System.Threading.Tasks.Task BTittle_update_statusTittle_7Async(string Id_Title) {
            return base.Channel.BTittle_update_statusTittle_7Async(Id_Title);
        }
        
        public WABlockchain.SWLNBlockchainService.EBTittle[] BTittle_O_State2() {
            return base.Channel.BTittle_O_State2();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> BTittle_O_State2Async() {
            return base.Channel.BTittle_O_State2Async();
        }
        
        public WABlockchain.SWLNBlockchainService.EBTittle[] BTittle_O_State3() {
            return base.Channel.BTittle_O_State3();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> BTittle_O_State3Async() {
            return base.Channel.BTittle_O_State3Async();
        }
        
        public WABlockchain.SWLNBlockchainService.EBTittle[] BTittle_O_State4() {
            return base.Channel.BTittle_O_State4();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> BTittle_O_State4Async() {
            return base.Channel.BTittle_O_State4Async();
        }
        
        public WABlockchain.SWLNBlockchainService.EBTittle[] BTittle_O_State5() {
            return base.Channel.BTittle_O_State5();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> BTittle_O_State5Async() {
            return base.Channel.BTittle_O_State5Async();
        }
        
        public WABlockchain.SWLNBlockchainService.EBTittle[] BTittle_O_State6() {
            return base.Channel.BTittle_O_State6();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> BTittle_O_State6Async() {
            return base.Channel.BTittle_O_State6Async();
        }
        
        public WABlockchain.SWLNBlockchainService.EBTittle[] BTittle_O_State7() {
            return base.Channel.BTittle_O_State7();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> BTittle_O_State7Async() {
            return base.Channel.BTittle_O_State7Async();
        }
        
        public WABlockchain.SWLNBlockchainService.EBTittle[] BTittle_O_TO_Upload() {
            return base.Channel.BTittle_O_TO_Upload();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBTittle[]> BTittle_O_TO_UploadAsync() {
            return base.Channel.BTittle_O_TO_UploadAsync();
        }
        
        public void Actualizar_ITitle_statusTitle_2(string Id_Title) {
            base.Channel.Actualizar_ITitle_statusTitle_2(Id_Title);
        }
        
        public System.Threading.Tasks.Task Actualizar_ITitle_statusTitle_2Async(string Id_Title) {
            return base.Channel.Actualizar_ITitle_statusTitle_2Async(Id_Title);
        }
        
        public void Actualizar_ITitle_statusTitle_1(string Id_Title) {
            base.Channel.Actualizar_ITitle_statusTitle_1(Id_Title);
        }
        
        public System.Threading.Tasks.Task Actualizar_ITitle_statusTitle_1Async(string Id_Title) {
            return base.Channel.Actualizar_ITitle_statusTitle_1Async(Id_Title);
        }
        
        public void Eliminar_ITitle_statusTitle(string Id_Title) {
            base.Channel.Eliminar_ITitle_statusTitle(Id_Title);
        }
        
        public System.Threading.Tasks.Task Eliminar_ITitle_statusTitleAsync(string Id_Title) {
            return base.Channel.Eliminar_ITitle_statusTitleAsync(Id_Title);
        }
        
        public void Actualizar_ITitle(string Id_Title, string carreer, string faculty, string fullName) {
            base.Channel.Actualizar_ITitle(Id_Title, carreer, faculty, fullName);
        }
        
        public System.Threading.Tasks.Task Actualizar_ITitleAsync(string Id_Title, string carreer, string faculty, string fullName) {
            return base.Channel.Actualizar_ITitleAsync(Id_Title, carreer, faculty, fullName);
        }
        
        public void Actualizar_BTittle_ConfirmarEntrega(string fullName, System.DateTime fecha, string modo) {
            base.Channel.Actualizar_BTittle_ConfirmarEntrega(fullName, fecha, modo);
        }
        
        public System.Threading.Tasks.Task Actualizar_BTittle_ConfirmarEntregaAsync(string fullName, System.DateTime fecha, string modo) {
            return base.Channel.Actualizar_BTittle_ConfirmarEntregaAsync(fullName, fecha, modo);
        }
        
        public WABlockchain.SWLNBlockchainService.EBRoluser[] Obtener_RolUser_O() {
            return base.Channel.Obtener_RolUser_O();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBRoluser[]> Obtener_RolUser_OAsync() {
            return base.Channel.Obtener_RolUser_OAsync();
        }
        
        public string UltimoID_O_NombreTablaSinElCaracterI(string NombreTabla) {
            return base.Channel.UltimoID_O_NombreTablaSinElCaracterI(NombreTabla);
        }
        
        public System.Threading.Tasks.Task<string> UltimoID_O_NombreTablaSinElCaracterIAsync(string NombreTabla) {
            return base.Channel.UltimoID_O_NombreTablaSinElCaracterIAsync(NombreTabla);
        }
        
        public string SiguienteID_O_NombreTablaSinElCaracterI(string NombreTabla) {
            return base.Channel.SiguienteID_O_NombreTablaSinElCaracterI(NombreTabla);
        }
        
        public System.Threading.Tasks.Task<string> SiguienteID_O_NombreTablaSinElCaracterIAsync(string NombreTabla) {
            return base.Channel.SiguienteID_O_NombreTablaSinElCaracterIAsync(NombreTabla);
        }
        
        public WABlockchain.SWLNBlockchainService.ENPerson Obtener_Persona_O_Estudiante() {
            return base.Channel.Obtener_Persona_O_Estudiante();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.ENPerson> Obtener_Persona_O_EstudianteAsync() {
            return base.Channel.Obtener_Persona_O_EstudianteAsync();
        }
        
        public WABlockchain.SWLNBlockchainService.ENPerson[] Obtener_Persona_O_EstudianteL() {
            return base.Channel.Obtener_Persona_O_EstudianteL();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.ENPerson[]> Obtener_Persona_O_EstudianteLAsync() {
            return base.Channel.Obtener_Persona_O_EstudianteLAsync();
        }
        
        public WABlockchain.SWLNBlockchainService.ENPerson[] Obtener_Persona_O_Nombre(string Fullname) {
            return base.Channel.Obtener_Persona_O_Nombre(Fullname);
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.ENPerson[]> Obtener_Persona_O_NombreAsync(string Fullname) {
            return base.Channel.Obtener_Persona_O_NombreAsync(Fullname);
        }
        
        public WABlockchain.SWLNBlockchainService.ENPerson[] Obtener_Persona_O() {
            return base.Channel.Obtener_Persona_O();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.ENPerson[]> Obtener_Persona_OAsync() {
            return base.Channel.Obtener_Persona_OAsync();
        }
        
        public WABlockchain.SWLNBlockchainService.ENCareer Obtener_Carrerra_O_ID_Pedro(string id) {
            return base.Channel.Obtener_Carrerra_O_ID_Pedro(id);
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.ENCareer> Obtener_Carrerra_O_ID_PedroAsync(string id) {
            return base.Channel.Obtener_Carrerra_O_ID_PedroAsync(id);
        }
        
        public WABlockchain.SWLNBlockchainService.IUserCareerCompleja[] U_Obtener_UserCareerComplejas_O_Est() {
            return base.Channel.U_Obtener_UserCareerComplejas_O_Est();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.IUserCareerCompleja[]> U_Obtener_UserCareerComplejas_O_EstAsync() {
            return base.Channel.U_Obtener_UserCareerComplejas_O_EstAsync();
        }
        
        public WABlockchain.SWLNBlockchainService.IUserCareerCompleja[] U_Obtener_UserCareerComplejas_O_Person() {
            return base.Channel.U_Obtener_UserCareerComplejas_O_Person();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.IUserCareerCompleja[]> U_Obtener_UserCareerComplejas_O_PersonAsync() {
            return base.Channel.U_Obtener_UserCareerComplejas_O_PersonAsync();
        }
        
        public WABlockchain.SWLNBlockchainService.IUserCareerCompleja[] U_Obtener_UserCareerComplejas_O_Est_Bus(string Fullname) {
            return base.Channel.U_Obtener_UserCareerComplejas_O_Est_Bus(Fullname);
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.IUserCareerCompleja[]> U_Obtener_UserCareerComplejas_O_Est_BusAsync(string Fullname) {
            return base.Channel.U_Obtener_UserCareerComplejas_O_Est_BusAsync(Fullname);
        }
        
        public WABlockchain.SWLNBlockchainService.IUserCareerCompleja[] U_Obtener_UserCareerComplejas_O_Est_ID(int ID) {
            return base.Channel.U_Obtener_UserCareerComplejas_O_Est_ID(ID);
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.IUserCareerCompleja[]> U_Obtener_UserCareerComplejas_O_Est_IDAsync(int ID) {
            return base.Channel.U_Obtener_UserCareerComplejas_O_Est_IDAsync(ID);
        }
    }
}
