//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WABlockchain.SWLNBlockchainService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EBUser", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EBUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdRolUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNetvalleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRolUser {
            get {
                return this.IdRolUserField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRolUserField, value) != true)) {
                    this.IdRolUserField = value;
                    this.RaisePropertyChanged("IdRolUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdTitle {
            get {
                return this.IdTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTitleField, value) != true)) {
                    this.IdTitleField = value;
                    this.RaisePropertyChanged("IdTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUser {
            get {
                return this.IdUserField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUserField, value) != true)) {
                    this.IdUserField = value;
                    this.RaisePropertyChanged("IdUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserNetvalle {
            get {
                return this.UserNetvalleField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNetvalleField, value) != true)) {
                    this.UserNetvalleField = value;
                    this.RaisePropertyChanged("UserNetvalle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EBRoluser", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EBRoluser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idrolUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idrolUser {
            get {
                return this.idrolUserField;
            }
            set {
                if ((object.ReferenceEquals(this.idrolUserField, value) != true)) {
                    this.idrolUserField = value;
                    this.RaisePropertyChanged("idrolUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SWLNBlockchainService.ISWLNBlockchain")]
    public interface ISWLNBlockchain {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_User_O", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_User_OResponse")]
        WABlockchain.SWLNBlockchainService.EBUser[] Obtener_User_O();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_User_O", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_User_OResponse")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBUser[]> Obtener_User_OAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/btener_BUser_O_iduser", ReplyAction="http://tempuri.org/ISWLNBlockchain/btener_BUser_O_iduserResponse")]
        WABlockchain.SWLNBlockchainService.EBUser btener_BUser_O_iduser(string Id_Carrera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/btener_BUser_O_iduser", ReplyAction="http://tempuri.org/ISWLNBlockchain/btener_BUser_O_iduserResponse")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBUser> btener_BUser_O_iduserAsync(string Id_Carrera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Insertar_BUser_I_idUser_email", ReplyAction="http://tempuri.org/ISWLNBlockchain/Insertar_BUser_I_idUser_emailResponse")]
        void Insertar_BUser_I_idUser_email(string Id_User, string Email, string password, string userNetvalle, string idrolUser, string idTitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Insertar_BUser_I_idUser_email", ReplyAction="http://tempuri.org/ISWLNBlockchain/Insertar_BUser_I_idUser_emailResponse")]
        System.Threading.Tasks.Task Insertar_BUser_I_idUser_emailAsync(string Id_User, string Email, string password, string userNetvalle, string idrolUser, string idTitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Actualizar_BUser_I_idUser_email", ReplyAction="http://tempuri.org/ISWLNBlockchain/Actualizar_BUser_I_idUser_emailResponse")]
        void Actualizar_BUser_I_idUser_email(string Email, string password, string userNetvalle, string idrolUser, string idTitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Actualizar_BUser_I_idUser_email", ReplyAction="http://tempuri.org/ISWLNBlockchain/Actualizar_BUser_I_idUser_emailResponse")]
        System.Threading.Tasks.Task Actualizar_BUser_I_idUser_emailAsync(string Email, string password, string userNetvalle, string idrolUser, string idTitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Insertar_BTitle_I_idTitle_faculty", ReplyAction="http://tempuri.org/ISWLNBlockchain/Insertar_BTitle_I_idTitle_facultyResponse")]
        void Insertar_BTitle_I_idTitle_faculty(string faculty, string carreer, string statusTittle, System.DateTime dateDelivery, string statusDelivery, string idUser, string fullnameTitulado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Insertar_BTitle_I_idTitle_faculty", ReplyAction="http://tempuri.org/ISWLNBlockchain/Insertar_BTitle_I_idTitle_facultyResponse")]
        System.Threading.Tasks.Task Insertar_BTitle_I_idTitle_facultyAsync(string faculty, string carreer, string statusTittle, System.DateTime dateDelivery, string statusDelivery, string idUser, string fullnameTitulado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_RolUser_O", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_RolUser_OResponse")]
        WABlockchain.SWLNBlockchainService.EBRoluser[] Obtener_RolUser_O();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/Obtener_RolUser_O", ReplyAction="http://tempuri.org/ISWLNBlockchain/Obtener_RolUser_OResponse")]
        System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBRoluser[]> Obtener_RolUser_OAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/UltimoID_O_NombreTablaSinElCaracterI", ReplyAction="http://tempuri.org/ISWLNBlockchain/UltimoID_O_NombreTablaSinElCaracterIResponse")]
        string UltimoID_O_NombreTablaSinElCaracterI(string NombreTabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/UltimoID_O_NombreTablaSinElCaracterI", ReplyAction="http://tempuri.org/ISWLNBlockchain/UltimoID_O_NombreTablaSinElCaracterIResponse")]
        System.Threading.Tasks.Task<string> UltimoID_O_NombreTablaSinElCaracterIAsync(string NombreTabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/SiguienteID_O_NombreTablaSinElCaracterI", ReplyAction="http://tempuri.org/ISWLNBlockchain/SiguienteID_O_NombreTablaSinElCaracterIRespons" +
            "e")]
        string SiguienteID_O_NombreTablaSinElCaracterI(string NombreTabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLNBlockchain/SiguienteID_O_NombreTablaSinElCaracterI", ReplyAction="http://tempuri.org/ISWLNBlockchain/SiguienteID_O_NombreTablaSinElCaracterIRespons" +
            "e")]
        System.Threading.Tasks.Task<string> SiguienteID_O_NombreTablaSinElCaracterIAsync(string NombreTabla);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISWLNBlockchainChannel : WABlockchain.SWLNBlockchainService.ISWLNBlockchain, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWLNBlockchainClient : System.ServiceModel.ClientBase<WABlockchain.SWLNBlockchainService.ISWLNBlockchain>, WABlockchain.SWLNBlockchainService.ISWLNBlockchain {
        
        public SWLNBlockchainClient() {
        }
        
        public SWLNBlockchainClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWLNBlockchainClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWLNBlockchainClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWLNBlockchainClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WABlockchain.SWLNBlockchainService.EBUser[] Obtener_User_O() {
            return base.Channel.Obtener_User_O();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBUser[]> Obtener_User_OAsync() {
            return base.Channel.Obtener_User_OAsync();
        }
        
        public WABlockchain.SWLNBlockchainService.EBUser btener_BUser_O_iduser(string Id_Carrera) {
            return base.Channel.btener_BUser_O_iduser(Id_Carrera);
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBUser> btener_BUser_O_iduserAsync(string Id_Carrera) {
            return base.Channel.btener_BUser_O_iduserAsync(Id_Carrera);
        }
        
        public void Insertar_BUser_I_idUser_email(string Id_User, string Email, string password, string userNetvalle, string idrolUser, string idTitle) {
            base.Channel.Insertar_BUser_I_idUser_email(Id_User, Email, password, userNetvalle, idrolUser, idTitle);
        }
        
        public System.Threading.Tasks.Task Insertar_BUser_I_idUser_emailAsync(string Id_User, string Email, string password, string userNetvalle, string idrolUser, string idTitle) {
            return base.Channel.Insertar_BUser_I_idUser_emailAsync(Id_User, Email, password, userNetvalle, idrolUser, idTitle);
        }
        
        public void Actualizar_BUser_I_idUser_email(string Email, string password, string userNetvalle, string idrolUser, string idTitle) {
            base.Channel.Actualizar_BUser_I_idUser_email(Email, password, userNetvalle, idrolUser, idTitle);
        }
        
        public System.Threading.Tasks.Task Actualizar_BUser_I_idUser_emailAsync(string Email, string password, string userNetvalle, string idrolUser, string idTitle) {
            return base.Channel.Actualizar_BUser_I_idUser_emailAsync(Email, password, userNetvalle, idrolUser, idTitle);
        }
        
        public void Insertar_BTitle_I_idTitle_faculty(string faculty, string carreer, string statusTittle, System.DateTime dateDelivery, string statusDelivery, string idUser, string fullnameTitulado) {
            base.Channel.Insertar_BTitle_I_idTitle_faculty(faculty, carreer, statusTittle, dateDelivery, statusDelivery, idUser, fullnameTitulado);
        }
        
        public System.Threading.Tasks.Task Insertar_BTitle_I_idTitle_facultyAsync(string faculty, string carreer, string statusTittle, System.DateTime dateDelivery, string statusDelivery, string idUser, string fullnameTitulado) {
            return base.Channel.Insertar_BTitle_I_idTitle_facultyAsync(faculty, carreer, statusTittle, dateDelivery, statusDelivery, idUser, fullnameTitulado);
        }
        
        public WABlockchain.SWLNBlockchainService.EBRoluser[] Obtener_RolUser_O() {
            return base.Channel.Obtener_RolUser_O();
        }
        
        public System.Threading.Tasks.Task<WABlockchain.SWLNBlockchainService.EBRoluser[]> Obtener_RolUser_OAsync() {
            return base.Channel.Obtener_RolUser_OAsync();
        }
        
        public string UltimoID_O_NombreTablaSinElCaracterI(string NombreTabla) {
            return base.Channel.UltimoID_O_NombreTablaSinElCaracterI(NombreTabla);
        }
        
        public System.Threading.Tasks.Task<string> UltimoID_O_NombreTablaSinElCaracterIAsync(string NombreTabla) {
            return base.Channel.UltimoID_O_NombreTablaSinElCaracterIAsync(NombreTabla);
        }
        
        public string SiguienteID_O_NombreTablaSinElCaracterI(string NombreTabla) {
            return base.Channel.SiguienteID_O_NombreTablaSinElCaracterI(NombreTabla);
        }
        
        public System.Threading.Tasks.Task<string> SiguienteID_O_NombreTablaSinElCaracterIAsync(string NombreTabla) {
            return base.Channel.SiguienteID_O_NombreTablaSinElCaracterIAsync(NombreTabla);
        }
    }
}
